### ISSUE TITLE
What about to have separate files for hashes, creds, logins and domains?

### ISSUE THREAD

**Issue by alxchk** [Raikia/CredNinja#1]
Sometimes it's usefull to bruteforce different combinations of logins and hashes

**Comment by Raikia** [comment]
I can add that.  I wouldn't use this method for bruteforcing logins of domain accounts, as it can extremely easily lockout accounts.  However, local accounts that may not have lockouts enabled (pretty typical to have it off for local) could be useful for this.

I'll add it soon.
