### ISSUE TITLE
Requires -a argument when scanning to see if SMB is open

### ISSUE THREAD

**Issue by kerbroasted** [Raikia/CredNinja#8]
Hi, slight improvement, noticed CredNinja requires -a --accounts argument when using the --scan argument to scan for hosts with only SMB open.

./CredNinja.py -s 192.168.100.125 --scan
CredNinja.py: error: the following arguments are required: -a/--accounts

You don't need a set of credentials to scan for SMB on hosts.

**Comment by Raikia** [comment]
CredNinja isn't intended to replace something like Nmap.  The use of the --scan argument is purely to ensure an old scan is up-to-date or to as an assistant to check live hosts if you provide it an unscanned range.  If you are simply intending to see if SMB is available on a host, I recommend simply doing "nmap -p 445 ..." as that is essentially what CredNinja is doing with --scan.
